// docs/components/AppHeader.vue
<template>
  <header class="app-header">
    <GoNavDrawer ref="mobileMenu" label="Mobile" :items="navItems" auto-close></GoNavDrawer>

    <GoHeaderBar breakpoint="tablet">
      <GoButton slot="mobile-menu-trigger" aria-label="menu" icon flat variant="text" @click="handleMobileTriggerClick">
        <GoIcon decorative icon-set="bx" name="menu" size="1.5rem"></GoIcon>
      </GoButton>

      <NuxtLink custom to="/" v-slot="{ href, navigate }">
        <GoGovAuLogo slot="logo" :href="href" @click="navigate">
          <img slot="main-brand" src="~/assets/img/logo.svg" :alt="siteConfig.name" />
          <img slot="main-brand-on-dark" src="~/assets/img/logo.svg" :alt="siteConfig.name" />
          <div slot="co-brand">
            <div class="text-size-1">
              <b>{{ siteConfig.name }}</b>
            </div>
            <div class="text-size-0 d-none d-block-tablet">{{ siteConfig.tagline }}</div>
          </div>
        </GoGovAuLogo>
      </NuxtLink>

      <div class="nav-actions" slot="actions">
        <GoButton v-bind="repoLinkProps" variant="text" icon round flat compact :aria-label="siteConfig.repoLink.label">
          <go-icon size="1.5rem" icon-set="bxl" name="github"></go-icon>
        </GoButton>

        <GoDarkMode ref="themer" @themechange="updateThemeIcon"></GoDarkMode>

        <GoButton variant="text" icon round flat compact @click="toggleDarkMode">
          <go-icon size="1.5rem" icon-set="bx" :name="themeIcon"></go-icon>
        </GoButton>
        <div v-if="siteConfig?.algolia" id="algolia-search" class="algolia"></div>
      </div>

      <go-main-nav slot="main-nav" :items="navItems"></go-main-nav>
    </GoHeaderBar>
  </header>
</template>

<script lang="ts" setup>
import { GoNavDrawer, GoHeaderBar, GoButton, GoIcon, GoMainNav, GoGovAuLogo, GoDarkMode } from '@go-ui/vue';

const repoLinkProps = {
  target: '_blank',
  href: siteConfig.repoLink.url,
  rel: 'noopener noreferrer nofollow',
};
const navItems = prepareNavItems(siteConfig.navbar.main);
</script>

<script lang="ts">
declare global {
  var docsearch: any;
}
export default defineComponent({
  data() {
    return {
      currentTheme: 'light',
    };
  },
  computed: {
    themeIcon() {
      return this.currentTheme === 'light' ? 'sun' : 'moon';
    },
  },
  mounted() {
    if (siteConfig.algolia && typeof docsearch === 'function') {
      const { appId, apiKey, indexName } = siteConfig.algolia;
      docsearch({
        appId,
        apiKey,
        indexName,
        container: '#algolia-search',
        debug: false, // Set debug to true if you want to inspect the modal
      });
    }
  },
  methods: {
    handleMobileTriggerClick() {
      (this.$refs.mobileMenu as any).$el.open();
    },
    toggleDarkMode() {
      (this.$refs.themer as any).$el.setTheme(this.currentTheme === 'light' ? 'dark' : 'light');
    },
    updateThemeIcon(e: any) {
      this.currentTheme = e.detail.theme;
    },
  },
});
</script>

<style lang="scss" scoped>
.app-header {
  position: sticky;
  top: 0;
  background: var(--go-color-bg);
  z-index: var(--layer-3);
}
.nav-actions {
  display: flex;
  align-items: center;
  gap: 1rem;
}
</style>

// packages/gopress/template/.gopress/src/components/app-header/app-header.tsx
import { INavItem } from '@go-ui/core/dist/types/interfaces';
import { href } from 'stencil-router-v2';
import { Build, Component, Prop, State, h } from '@stencil/core';

import siteConfig from '../../../config';
import { prepareNavItems } from '../../utils/helpers';
import themeStore from '../../stores/theme.store';

declare global {
  var docsearch: any;
}

@Component({
  tag: 'app-header',
  styleUrl: 'app-header.scss',
  shadow: false,
})
export class AppHeader {
  @Prop() inline = false;

  @State() navItems: INavItem[] = [];

  @Prop() activePath: string = '/';

  componentWillLoad() {
    this.loadTheme();

    this.navItems = prepareNavItems(siteConfig.navbar.main, '');
  }

  /**
   * load either light/dark theme according to
   * - operating system preference
   * - localStorage override
   */
  loadTheme() {
    // check if there's any local storage override
    // match OS preference
    this.setHtmlAttribute();
  }

  setHtmlAttribute() {
    document.documentElement.setAttribute('data-theme', themeStore.state.currentTheme);
  }

  toggleDarkMode() {
    themeStore.state.currentTheme = themeStore.state.currentTheme === 'light' ? 'dark' : 'light';
    this.setHtmlAttribute();
    localStorage.setItem('go-ui-theme', themeStore.state.currentTheme);
  }

  // @Watch('activePath')
  // setActivePath(newValue: string) {
  //   this.navItems = this.navItems.map(item => {
  //     const cleanPathname = removeLeadingSlash(newValue);
  //     const cleanUrl = removeLeadingSlash(item.url);
  //     return {
  //       ...item,
  //       isCurrent: cleanPathname.includes(cleanUrl),
  //     };
  //   });
  // }

  mobileMenu: HTMLGoNavDrawerElement;

  handleMobileTriggerClick() {
    this.mobileMenu.open();
  }

  componentDidLoad() {
    if (Build.isBrowser && siteConfig['algolia']) {
      const { appId, apiKey, indexName } = siteConfig['algolia'];
      docsearch({
        appId,
        apiKey,
        indexName,
        container: '#algolia-search',
        debug: false, // Set debug to true if you want to inspect the modal
      });
    }
  }

  render() {
    const { navItems } = this;
    const repoLinkProps = {
      target: '_blank',
      href: siteConfig.repoLink.url,
      rel: 'noopener noreferrer nofollow',
    };
    const themeIcons = {
      light: 'sun',
      dark: 'moon',
    };
    return (
      <header>
        <go-nav-drawer ref={(el) => (this.mobileMenu = el)} label="Menu" items={navItems} autoClose={true}></go-nav-drawer>
        <go-header-bar breakpoint="tablet">
          <go-button slot="mobile-menu-trigger" aria-labelledby="menu-label" compact flat stack variant="text" onClick={() => this.handleMobileTriggerClick()}>
            <go-icon icon-set="bx" name="menu" size="1.5rem" slot="prefix"></go-icon>
            <span id="menu-label">Menu</span>
          </go-button>

          <go-gov-au-logo {...href('/')} slot="logo">
            <img slot="main-brand" src={siteConfig.logo} alt={siteConfig.name} />
            <img slot="main-brand-on-dark" src={siteConfig.logoDark} alt={siteConfig.name} />
            <div slot="co-brand">
              <div class="text-size-1">
                <b>{siteConfig.name}</b>
              </div>
              {siteConfig.tagline && <div class="text-size-0 d-none d-block-desktop">{siteConfig.tagline}</div>}
            </div>
          </go-gov-au-logo>

          <div class="nav-actions" slot="actions">
            <go-button {...repoLinkProps} variant="text" icon round flat compact aria-label={siteConfig.repoLink.label}>
              <go-icon size="1.5rem" icon-set="bxl" name="github"></go-icon>
            </go-button>
            {siteConfig.darkThemeSwitch && (
              <go-button
                aria-label={`Switch to ${themeStore.state.currentTheme} mode`}
                variant="text"
                icon
                round
                flat
                compact
                onClick={() => this.toggleDarkMode()}>
                <go-icon size="1.5rem" icon-set="bx" name={themeIcons[themeStore.state.currentTheme]}></go-icon>
              </go-button>
            )}
            {siteConfig['algolia'] ? <div id="algolia-search" class="algolia"></div> : null}
          </div>

          <go-main-nav slot="main-nav" items={navItems}></go-main-nav>
        </go-header-bar>
      </header>
    );
  }
}
